### PR TITLE
Smart meter management

### PR DESCRIPTION
**Pull request by 1r-1na**
- SmartMetersPage.tsx as page to show all smart meters
- Add-form to add a smart meter
- SmartMeterDetailsPage.tsx to show smart meter details and add metadata.

### CODE REVIEW

**Review by Essiga — CHANGES_REQUESTED** [review]
image
UI breaks when scrolling down
Missing: Creation of Metadata on creation of smart meter and possibility to also add/change metadata later as discussed in discord chat

**Review by Smightym8 — CHANGES_REQUESTED** [review]
- The breadcrumbs are shown twice. 
- Remove "Smart Meter Details" from the navigation, a user should click on a smart meter to view the details. 
- The `Add Metadata` button is only shown if a smart meter is created. When visiting the smart meters page again the button is not visible anymore.
- The endpoint to get the smart meters is called twice.

image

**Review by Smightym8 — APPROVED** [review]
lgtm

**Review by Smightym8 — APPROVED** [review]

**Review by Essiga — APPROVED** [review]
lgtm

**Pull request merged**
